name: Rebase

on:
  schedule: [cron: '0 0 * * *']
  workflow_dispatch:

jobs:
  build:
    name: Automatic rebase
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch LineageOS repo
      run: |
        git config user.name "San4255"
        git config user.email "sansaxena0@gmail.com"
        git fetch https://github.com/LineageOS/android_frameworks_base lineage-20.0

    - name: Rebase
      run: |
        git rebase FETCH_HEAD

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
